Models/Property.cs
using System.ComponentModel.DataAnnotations;

namespace Emoloyee_Property_Mangment_Task.Models
{
    public class Property:BaseModel
    {
        [Attribute.UniqueProperty]
        public string Name { get; set; }
     
        public PropertyType propertyType   { get; set; }
        public bool IsRequired { get; set; }

        [Attribute.DropDownValues]
        public string? DropDownValues { get; set; }
        public HashSet<EmployeeProperty>? EmployeeProperties { get; set; }


    }
}

Models/PropertyType.cs
namespace Emoloyee_Property_Mangment_Task.Models
{

    public enum PropertyType
    {
        String=0,
        Int=2,  
        DropDown=4,
        Date=6
    }
}

Controllers/PropertyController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Emoloyee_Property_Mangment_Task.Services;
using Emoloyee_Property_Mangment_Task.Services.PropertyService;
using Mapster;
using Emoloyee_Property_Mangment_Task.ViewModel;
using Emoloyee_Property_Mangment_Task.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using Emoloyee_Property_Mangment_Task.Dto.PropertyDto;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore;

namespace Emoloyee_Property_Mangment_Task.Controllers
{
    public class PropertyController : Controller
    {
        IPropertyService _propertyService;
        public PropertyController(IPropertyService propertyService)
        {
        _propertyService = propertyService;
        }
        public ActionResult Index()
        {
            var propertiesDto = _propertyService.GetAll().AsNoTracking() .ToList();
            var propertiesViewModel=propertiesDto.Adapt<List<PropertyViewModel>>();
            return View(propertiesViewModel);
        }

        public ActionResult Create()
        {
            ViewBag.isEdit = false;
            ViewBag.TypeList = new SelectList(Enum.GetValues(typeof(PropertyType)));
            return View("Create",new PropertyViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async  Task< ActionResult> Create(PropertyViewModel propertyViewModel)
        {
            ViewBag.TypeList = new SelectList(Enum.GetValues(typeof(PropertyType)));
            ViewBag.isEdit=false;
                
            try
            {
                if (ModelState.IsValid)
                {
                    var propertyDto = propertyViewModel.Adapt<PropertyDto>();
                    if (await _propertyService.Add(propertyDto))
                    {
                        return RedirectToAction(nameof(Index));

                    }
                    else
                    {
                        return View(propertyViewModel);
                    }

                }
                else
                {
                    return View(propertyViewModel);
                }

            }
            catch
            {
                throw new Exception("error in db");

            }
        }
        public ActionResult Edit(int id)
        {
            ViewBag.TypeList = new SelectList(Enum.GetValues(typeof(PropertyType)));

            ViewBag.IsEdit = true;
            var propertyViewModel = _propertyService.GetById(id).Adapt<PropertyViewModel>();  

            return View("Create",propertyViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(PropertyViewModel propertyViewModel)
        {
            ViewBag.TypeList = new SelectList(Enum.GetValues(typeof(PropertyType)));
            ViewBag.IsEdit = true;

            try
            {
                if (ModelState.IsValid)
                {
                    var propertyDto = propertyViewModel.Adapt<PropertyDto>();
                    bool isEDit = await _propertyService.Update(propertyDto);
                    if (isEDit)
                    {

                        return RedirectToAction(nameof(Index));
                    }
                    else
                        return View("Create", propertyViewModel);
                }
                else
                {
                    return View("Create", propertyViewModel);
                }

            }
            catch 
            {
                throw new Exception("error in editing");   
                    }
        }

        public async Task< ActionResult> Delete(int id)
        {
            try
            {
                bool isDeleted = await _propertyService.Delete(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                throw new Exception("Error in Deleting");
            }
           
        }

       
    }
}

Views/Property/Create.cshtml
@{
    var Types = ViewBag.TypeList as SelectList;
}
@model Emoloyee_Property_Mangment_Task.ViewModel.PropertyViewModel
@addTagHelper * , @Microsoft.AspNetCore.Mvc
@addTagHelper * ,@Emoloyee_Property_Mangment_Task


<form method="post" asp-controller="Property">
    
    <div asp-validation-summary="All" class="text-danger"></div>

    <input asp-for="Id" type="hidden" value="@Model.Id">
    <input asp-for="Value" type="hidden" value="@Model.Id">



    <div class="form-group">
        <label asp-for="@Model.Name">Property Name</label>
        <input asp-for="@Model.Name" type="text" class=" form-control" placeholder="salary">
        <span asp-validation-for="@Model.Name" class="text-danger"></span>

    </div>
    <div class="form-group">
        <label asp-for="propertyType">Property Type</label>
        <select asp-for="propertyType" asp-items="Types" class="form-control" id="Types">
            <option value=""> select role </option>
        </select>


    </div>
    
    <div class="form-group">
        <label asp-for="@Model.DropDownValues">DropDown Values</label>
        <input asp-for="@Model.DropDownValues" type="text" class=" form-control"  placeholder="seperated by -  if the property type is dropdown ">
        <span asp-validation-for="@Model.DropDownValues" class="text-danger"></span>

    </div>
    <div class="form-check">
        <label asp-for="IsRequired" class="form-check-label">Is Required</label>
        <input asp-for="IsRequired" class="form-check-input"  value="true"/>
        <span asp-validation-for="IsRequired" class="text-danger"></span>
    </div>
    
    
    @if (ViewBag.isEdit == false)
    {
        <div class="form-group">
            <input type="submit" value="submit" class="btn btn-secondary" asp-controller="Property" asp-action="Create" />
        </div>
    }
    @if (ViewBag.isEdit == true)
    {
        <div class="form-group">
            <input type="submit" value="Edit" class="btn btn-secondary " asp-action="Edit" />
        </div>}
    
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Views/Property/Index.cshtml
@using Emoloyee_Property_Mangment_Task.ViewModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


    @model List<PropertyViewModel>
@addTagHelper * , @Microsoft.AspNetCore.Mvc
@addTagHelper * ,@Emoloyee_Property_Mangment_Task

<div class="container mt-4">
    <h2>Property List</h2>

    <div class="table-responsive">
        <table class="table table-striped table-bordered table-hover">
            <thead class="thead-dark">
                <tr>
                    
                    
                        <th>Property Name </th>
                        <th>propertyType </th>
                        <th>IsRequired </th>
                        <th>DropDownValues </th>
                        <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var prop in Model)
                {
                    <tr>

                        <td>@prop.Name </td>
                        <td>@prop.propertyType </td>
                        <td>@prop.IsRequired </td>
                        <td>@prop.DropDownValues </td>
                        <td>  
                          <a href="@Url.Action("Edit", new { Id = prop.Id })" class="btn btn-sm btn-primary">
                                <i class="fas fa-edit"></i> Edit
                            </a>
                            <a href="@Url.Action("Delete", new { Id = prop.Id })"
                               class="btn btn-sm btn-danger"
                               onclick="return confirm('Are you sure you want to delete this item?');">


                                <i class="fas fa-info-circle"></i> Delete
                            </a>
                            </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

    <a href="@Url.Action("Create")" class="btn btn-success">
        <i class="fas fa-plus"></i> Add New Property
    </a>
</div>